#!/bin/sh

REALOP="$1"
TARGET=/dev/hdb
PASSWORD_OPT=" -a "
PASSWORD_SRC="Motherboard"

if [ -z "$1" ]; then
echo "usage: $0 <lock/unlock/disable-pw>"
exit 1
fi

if [ "$2" != "" ]; then
pass=$(echo $2 | grep hdpass.txt)
eeprom=$(echo $2 | grep eeprom.bin)
hddkey=$(echo $2 | grep hddkey.txt)
if [ -e "$2" ]; then
if [ "$eeprom" != "" ]; then 
PASSWORD_OPT="-e $2"
PASSWORD_SRC="$2"
elif [ "$pass" != "" ]; then
pass=$(cat $2)
if [ $pass -eq "TEAMASSEMBLY" ]; then
pass="5445414D414353454D424C59"
elif [ $pass -eq "XBOXSCENE" ]; then
pass="58424F585343454E4500"
fi
[ -z "$pass" ] && echo "$2 empty" && exit 1
PASSWORD_OPT="-p $pass"
else
hddkey=$(cat $2)
[ -z "$hddkey" ] && echo "$2 empty" && exit 1
PASSWORD_OPT="-k $hddkey"
fi
PASSWORD_SRC="$2"
fi
fi

if [ -e $TARGET ]; then
hdtool2  $PASSWORD_OPT -d $TARGET -o unlock | head -n 11 > /tmp/abc.$$
info=$(cat /tmp/abc.$$)
if [ "$1" != "unlock" ]; then
dialog --defaultno --title "Password from $PASSWORD_SRC, choose Yes to $1" --yesno "$info" 15 90
case $? in
  0 ) lock="yes";;
esac
rm /tmp/abc.$$
clear
if  [ "$lock" != "" ]; then
if  [ "$hddkey" != "" ]; then
hdtool2 -d $TARGET $PASSWORD_OPT -o disable-pw > /tmp/pass.$$
[ "$1" != "disable-pw" ] && echo "y" | hdtool2 -d $TARGET $PASSWORD_OPT -o $REALOP >> /tmp/pass.$$
else
hdtool -d $TARGET $PASSWORD_OPT -o disable-pw > /tmp/pass.$$
[ "$1" != "disable-pw" ] && echo "y" | hdtool -d $TARGET $PASSWORD_OPT -o $REALOP >> /tmp/pass.$$
fi
dialog  --title "Done, Password from $PASSWORD_SRC saved in /tmp/pass.$$" --textbox /tmp/pass.$$ 15 90
clear
fi
else
dialog --title "$1 result - password generated from $PASSWORD_SRC" --msgbox "$info" 15 90
clear
fi
fi
